language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email:
    recipients:
      - andreasnoackjensen@gmail.com
    # on_success: never

#script: # use the default script setting
#  - julia -e 'Pkg.init(); Pkg.add("RNGTest")'
#  - julia -e 'using RNGTest; @assert isdefined(:RNGTest); @assert typeof(RNGTest) === Module'
#  - julia test/runtests.jl
